import Layout from "./components/Layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Layout>
          {children} 
          {/** 라우팅으로 결정된 현재 페이지가 렌더링 되는 자리 */}
        </Layout>
      </body>
    </html>
  );
}
